# Generated by Django 5.2.7 on 2025-10-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da disciplina (ex: Matemática, História, etc.)', max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da disciplina', null=True)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do material de estudo', max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(help_text='Selecione o arquivo para upload', upload_to='materiais/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='portal_estudos.disciplina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'ordering': ['-data_upload'],
            },
        ),
    ]
